# Generated by Django 4.2.4 on 2023-08-16 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c2083c83-7c76-4ca5-b443-7a23b57e13f6'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('locccn', models.IntegerField(max_length=30)),
            ],
        ),
    ]
