# Generated by Django 4.2.4 on 2023-08-16 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d038bfc9-20ae-4ab5-b9fc-a4d57f69d909'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='locccn',
            field=models.IntegerField(),
        ),
    ]
