# Generated by Django 4.2.4 on 2023-08-17 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_book_id_alter_book_locccn'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default='jamie', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('03bdf6da-ee02-40f9-bed3-662b79cb7ff2'), primary_key=True, serialize=False),
        ),
    ]
