# Generated by Django 4.2.4 on 2023-08-18 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_book_author_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8c35f81-3205-4f1f-a304-a5656f2a8b52'), primary_key=True, serialize=False),
        ),
    ]
