# Generated by Django 4.2.4 on 2023-08-18 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b843682-eb16-44a6-bfb4-dc6a167f18d8'), primary_key=True, serialize=False),
        ),
    ]
